export const commoditiesConstants = {

    GET_COMMODITIES_LIST_REQUEST: "GET_COMMODITIES_LIST_REQUEST",
    GET_COMMODITIES_LIST_SUCCESS: "GET_COMMODITIES_LIST_SUCCESS",
    GET_COMMODITIES_LIST_FAILURE: "GET_COMMODITIES_LIST_FAILURE"

}