export const detailsConstants = {

    GET_DETAILS_LIST_REQUEST: "GET_DETAILS_LIST_REQUEST",
    GET_DETAILS_LIST_SUCCESS: "GET_DETAILS_LIST_SUCCESS",
    GET_DETAILS_LIST_FAILURE: "GET_DETAILS_LIST_FAILURE"

}